### ISSUE TITLE
输入App ID之后的提示信息错误

### ISSUE THREAD

**Issue by zengxs** [bookfere/KindleEar-Uploader#1]

**Comment by kindlefere** [comment]
提示的是什么错误呢？

**Comment by zengxs** [comment]
[uploader.sh#L36](https://github.com/kindlefere/KindleEar-Uploader/blob/master/uploader.sh#L36)

**Comment by kindlefere** [comment]
注意冒号后面要有空格。

**Comment by kindlefere** [comment]
这一行有什么问题？输入 APPID 后如果出现错误，应该是有具体提示信息的呀。
