### ISSUE TITLE
显示wrong SRC_EMAIL

### ISSUE THREAD

**Issue by xiaotianxt** [bookfere/KindleEar-Uploader#3]
显示wrong SRC_EMAIL 我已经按照教程修改了邮箱 但是还有这个 请问是怎么回事?

**Comment by kindlefere** [comment]
在“APP 引擎”中的“设置”页面，在“应用设置”标签项下点击【修改】按钮，在“Email API 获得授权的发件人”这一项里填入你的 Gmail 地址，点击【保存】按钮，确保保存成功。
