### ISSUE TITLE
注册只能gmail, 推送不能设置gmail

### ISSUE THREAD

**Issue by lucasjinreal** [bookfere/KindleEar-Uploader#5]
Hi, 亚马逊后台并不能设置非kindle.cn 后缀作为接受邮箱。。。。

**Comment by bookfere** [comment]
亚马逊后台并不需要设置接收邮箱。不太明白你要表达什么，建议描述详细一些。

**Comment by lucasjinreal** [comment]
你们注册只能gamail，亚马逊后台设置的接收邮箱默认是kindle.cn 

这能推？

**Comment by bookfere** [comment]
你在使用 KindleEar-Uploader 的哪一步遇到了这个问题？
